var WORDS = [
  {en:"abruptly", pos:"부", ko:"불쑥, 갑작스럽게", ipa:"əˈbrʌptli"},
  {en:"absorbing", pos:"형", ko:"몰입시키는, 정신을 빼앗는", ipa:"əbˈzɔrbɪŋ"},
  {en:"abutted", pos:"동", ko:"abut(맞닿다, 인접하다)의 과거형", ipa:"əˈbʌtɪd"},
  {en:"account", pos:"명", ko:"~때문에", ipa:"əˈkaʊnt"},
  {en:"accountant", pos:"명", ko:"회계사", ipa:"əˈkaʊntənt"},
  {en:"acid", pos:"명", ko:"산(산성 물질)", ipa:"ˈæsəd"},
  {en:"acknowledges", pos:"동", ko:"인정하다", ipa:"ækˈnɑlɪdʒɪz"},
  {en:"addition", pos:"명", ko:"게다가", ipa:"əˈdɪʃən"},
  {en:"admirably", pos:"부", ko:"훌륭하게, 감탄스러울 만큼", ipa:"ˈædmərəbli"},
  {en:"adventures", pos:"명", ko:"모험", ipa:"ædˈvɛntʃərz"},
  {en:"advertisement", pos:"명", ko:"광고", ipa:"ædˈvɜrtəzmənt"},
  {en:"affair", pos:"명", ko:"일, 사업", ipa:"əˈfɛr"},
  {en:"afraid", pos:"형", ko:"~인 줄 알고 걱정하는", ipa:"əˈfreɪd"},
  {en:"age", pos:"명", ko:"시대", ipa:"ˈeɪdʒ"},
  {en:"alternately", pos:"부", ko:"번갈아", ipa:"ˈɔltərnətli"},
  {en:"animated", pos:"형", ko:"활기찬", ipa:"ˈænəmeɪtɪd"},
  {en:"announcement", pos:"명", ko:"광고문, 공고", ipa:"əˈnaʊnsmənt"},
  {en:"answered", pos:"동", ko:"대답하다", ipa:"ˈænsərd"},
  {en:"apology", pos:"명", ko:"사과", ipa:"əˈpɑlədʒi"},
  {en:"applicant", pos:"명", ko:"지원자", ipa:"ˈæplɪkənt"},
  {en:"apply", pos:"동", ko:"지원하다, 신청하다", ipa:"əˈplaɪ"},
  {en:"armed", pos:"형", ko:"무장한", ipa:"ˈɑrmd"},
  {en:"arteries", pos:"명", ko:"간선도로, artery(동맥)의 복수형", ipa:"ˈɑrtəriz"},
  {en:"artificial", pos:"형", ko:"인공의", ipa:"ɑrtəˈfɪʃəl"},
  {en:"askance", pos:"부", ko:"의심스럽게, 곁눈질로", ipa:"əˈskæns"},
  {en:"assistants", pos:"명", ko:"assistant의 복수", ipa:"əˈsɪstənts"},
  {en:"astuteness", pos:"명", ko:"기민함, 영민함", ipa:"əˈstutnəs"},
  {en:"atmosphere", pos:"명", ko:"분위기, 공기", ipa:"ˈætməsfɪr"},
  {en:"autumn", pos:"명", ko:"가을", ipa:"ˈɔtəm"},
  {en:"avail", pos:"동", ko:"소용이 있다, 도움이 되다", ipa:"əˈveɪl"},
  {en:"awkward", pos:"형", ko:"곤란한, 난처한", ipa:"ˈɑkwərd"},
  {en:"bachelor", pos:"명", ko:"미혼 남성, 독신남", ipa:"ˈbætʃələr"},
  {en:"bade", pos:"동", ko:"bid(고하다, 인사하다)의 옛 과거형", ipa:"ˈbeɪd"},
  {en:"baggy", pos:"형", ko:"헐렁한", ipa:"ˈbægi"},
  {en:"barrow", pos:"명", ko:"(손으로 미는) 손수레", ipa:"ˈbæroʊ"},
  {en:"bashful", pos:"형", ko:"수줍은, 겸연쩍은", ipa:"ˈbæʃfəl"},
  {en:"belief", pos:"명", ko:"past belief = 믿기 어려운, 믿을 수 없는", ipa:"bɪˈlif"},
  {en:"benefactor", pos:"명", ko:"후원자, 은인", ipa:"ˈbɛnəfæktər"},
  {en:"bequest", pos:"명", ko:"유증, 유산", ipa:"bɪˈkwɛst"},
  {en:"berths", pos:"명", ko:"berth의 복수", ipa:"ˈbərθs"},
  {en:"better", pos:"동", ko:"자기 처지를 향상시키다", ipa:"ˈbɛtər"},
  {en:"beyond", pos:"전", ko:"~외에는, ~을 넘어서", ipa:"bɪˈɑnd"},
  {en:"bill", pos:"명", ko:"(새의) 부리", ipa:"ˈbɪl"},
  {en:"billet", pos:"명", ko:"원래는 병사의 숙소, 여기서는 일자리/자리", ipa:"ˈbɪlət"},
  {en:"bizarre", pos:"형", ko:"기이한", ipa:"bəˈzɑr"},
  {en:"black-letter", pos:"형", ko:"고딕체(옛 활자체)로 인쇄된", ipa:"ˈblækˌlɛtər"},
  {en:"blazing", pos:"형", ko:"활활 타오르는", ipa:"ˈbleɪzɪŋ"},
  {en:"blotting-paper", pos:"명", ko:"압지(잉크를 빨아들이는 종이)", ipa:"ˈblɑtɪŋˌpeɪpər"},
  {en:"body", pos:"명", ko:"여기서는 몸이 아니라 단체, 조직", ipa:"ˈbɑdi"},
  {en:"bore", pos:"동", ko:"bear의 과거형", ipa:"ˈbɔr"},
  {en:"bracelets", pos:"명", ko:"속어로 수갑", ipa:"ˈbreɪslɪts"},
  {en:"brassy", pos:"형", ko:"놋쇠로 된", ipa:"ˈbræsi"},
  {en:"breastpin", pos:"명", ko:"브로치, 가슴에 다는 핀", ipa:"ˈbrɛstpɪn"},
  {en:"budge", pos:"동", ko:"조금 움직이다, 자리를 뜨다(주로 부정문에서)", ipa:"ˈbʌdʒ"},
  {en:"called", pos:"동", ko:"~를 찾아가다", ipa:"ˈkɔld"},
  {en:"candid", pos:"형", ko:"솔직한", ipa:"ˈkændəd"},
  {en:"candidate", pos:"명", ko:"지원자, 후보자", ipa:"ˈkændədeɪt"},
  {en:"cardboard", pos:"명", ko:"마분지, 판지", ipa:"ˈkɑrdbɔrd"},
  {en:"carpenter", pos:"명", ko:"목수", ipa:"ˈkɑrpəntər"},
  {en:"cellar", pos:"명", ko:"지하실", ipa:"ˈsɛlər"},
  {en:"certainly", pos:"부", ko:"분명히", ipa:"ˈsɜrtənli"},
  {en:"chagrin", pos:"명", ko:"분함, 원통함", ipa:"ʃəˈgrɪn"},
  {en:"choked", pos:"형", ko:"(~로) 꽉 막힌, 발 디딜 틈 없이 붐비는", ipa:"ˈtʃoʊkt"},
  {en:"chronicle", pos:"동", ko:"기록으로 남기다", ipa:"ˈkrɑnɪkəl"},
  {en:"chuckled", pos:"동", ko:"킬킬 웃다", ipa:"ˈtʃʌkəld"},
  {en:"claim", pos:"명", ko:"권리, 자격", ipa:"ˈkleɪm"},
  {en:"clean-shaven", pos:"형", ko:"말끔히 면도한", ipa:"ˈklinˌʃeɪvən"},
  {en:"clever", pos:"형", ko:"영리한, 똑똑한", ipa:"ˈklɛvər"},
  {en:"colour", pos:"명", ko:"색깔(영국식 철자, color)", ipa:"ˈkʌlər"},
  {en:"column", pos:"명", ko:"(신문의) 난, 칼럼", ipa:"ˈkɑləm"},
  {en:"combinations", pos:"명", ko:"조합", ipa:"kɑmbəˈneɪʃənz"},
  {en:"comical", pos:"형", ko:"우스꽝스러운", ipa:"ˈkɑmɪkəl"},
  {en:"commerce", pos:"명", ko:"상업", ipa:"ˈkɑmərs"},
  {en:"committed", pos:"동", ko:"저지르다", ipa:"kəˈmɪtɪd"},
  {en:"commonplace", pos:"형", ko:"평범한", ipa:"ˈkɑmənpleɪs"},
  {en:"complain", pos:"동", ko:"불평하다", ipa:"kəmˈpleɪn"},
  {en:"complicates", pos:"동", ko:"complicate(복잡하게 만들다)의 3인칭 단수형", ipa:"ˈkɑmplɪkeɪts"},
  {en:"complimented", pos:"동", ko:"compliment A upon B = B에 대해 A를 칭찬하다", ipa:"ˈkɑmpləmɛntɪd"},
  {en:"comply", pos:"동", ko:"comply with = ~을 준수하다, 따르다", ipa:"kəmˈplaɪ"},
  {en:"composer", pos:"명", ko:"작곡가", ipa:"kəmˈpoʊzər"},
  {en:"conclusion", pos:"명", ko:"결론", ipa:"kənˈkluʒən"},
  {en:"conditions", pos:"명", ko:"condition(조건)의 복수형", ipa:"kənˈdɪʃənz"},
  {en:"confined", pos:"동", ko:"국한되다, 제한되다", ipa:"kənˈfaɪnd"},
  {en:"congratulate", pos:"동", ko:"congratulate A on B = B에 대해 A를 축하하다", ipa:"kənˈgrætʃəleɪt"},
  {en:"congratulated", pos:"동", ko:"축하하다", ipa:"kənˈgrætʃəleɪtɪd"},
  {en:"connected", pos:"동", ko:"얽혀 있는", ipa:"kəˈnɛktɪd"},
  {en:"consequential", pos:"형", ko:"거들먹거리는, 자기가 중요한 듯 구는", ipa:"kɑnsəˈkwɛnʃəl"},
  {en:"considerable", pos:"형", ko:"상당한, 꽤 많은", ipa:"kənˈsɪdərəbəl"},
  {en:"contemplative", pos:"형", ko:"사색적인", ipa:"kənˈtɛmplətɪv"},
  {en:"contrary", pos:"명", ko:"on the contrary = 오히려, 그와 반대로", ipa:"ˈkɑntrɛri"},
  {en:"contributed", pos:"동", ko:"기여하다, 글을 보태다", ipa:"kənˈtrɪbjutɪd"},
  {en:"conundrums", pos:"명", ko:"conundrum(수수께끼, 난제)의 복수형", ipa:"kəˈnʌndrəmz"},
  {en:"convenience", pos:"명", ko:"편의, 편의 시설", ipa:"kənˈvinjəns"},
  {en:"conventions", pos:"명", ko:"관습, 관례", ipa:"kənˈvɛnʃənz"},
  {en:"conversation", pos:"명", ko:"대화", ipa:"kɑnvərˈseɪʃən"},
  {en:"conveyed", pos:"동", ko:"convey(실어 나르다)의 과거형", ipa:"kənˈveɪd"},
  {en:"copier", pos:"명", ko:"베끼는 사람, 필경사", ipa:"ˈkɑpiər"},
  {en:"cordially", pos:"부", ko:"다정하게", ipa:"ˈkɔrdʒəli"},
  {en:"coster's", pos:"명", ko:"coster(과일/채소 노점상)의 소유격", ipa:"ˈkɔstərz"},
  {en:"course", pos:"명", ko:"경과, 흐름", ipa:"ˈkɔrs"},
  {en:"crib", pos:"명", ko:"(구어) 일자리, 자리", ipa:"ˈkrɪb"},
  {en:"crimes", pos:"명", ko:"범죄", ipa:"ˈkraɪmz"},
  {en:"cuff", pos:"명", ko:"소맷부리", ipa:"ˈkʌf"},
  {en:"cunning", pos:"형", ko:"교활한, 영리한", ipa:"ˈkʌnɪŋ"},
  {en:"curled", pos:"동", ko:"curl(몸을 웅크리다)의 과거형", ipa:"ˈkərld"},
  {en:"curt", pos:"형", ko:"짤막한, 퉁명스러운", ipa:"ˈkərt"},
  {en:"custom", pos:"명", ko:"버릇, 습관", ipa:"ˈkʌstəm"},
  {en:"dangling", pos:"동", ko:"매달려 늘어지다", ipa:"ˈdæŋgəlɪŋ"},
  {en:"daring", pos:"형", ko:"대담한", ipa:"ˈdɛrɪŋ"},
  {en:"deal", pos:"명", ko:"deal table = 소나무 등 값싼 목재로 만든 탁자", ipa:"ˈdil"},
  {en:"dealings", pos:"명", ko:"거래, 교류", ipa:"ˈdilɪŋz"},
  {en:"debts", pos:"명", ko:"debt의 복수", ipa:"ˈdɛts"},
  {en:"deceived", pos:"동", ko:"속이다, 기만하다", ipa:"dɪˈsivd"},
  {en:"deduce", pos:"동", ko:"추리해내다", ipa:"dɪˈdus"},
  {en:"deference", pos:"명", ko:"경의, 존중", ipa:"ˈdɛfərəns"},
  {en:"degrees", pos:"명", ko:"by degrees = 점차, 서서히", ipa:"dɪˈgriz"},
  {en:"dejected", pos:"형", ko:"낙담한, 풀 죽은", ipa:"dɪˈdʒɛktɪd"},
  {en:"delicate", pos:"형", ko:"은은한, 섬세한", ipa:"ˈdɛləkət"},
  {en:"dense", pos:"형", ko:"여기서는 둔한, 눈치 없는", ipa:"ˈdɛns"},
  {en:"depot", pos:"명", ko:"저장소, 작업장(제작소)", ipa:"ˈdipoʊ"},
  {en:"despair", pos:"명", ko:"절망", ipa:"dɪˈspɛr"},
  {en:"determined", pos:"동", ko:"determine to ~ = ~하기로 결심하다", ipa:"dɪˈtərmənd"},
  {en:"develop", pos:"동", ko:"(사진을) 현상하다", ipa:"dɪˈvɛləp"},
  {en:"devouring", pos:"형", ko:"여기서는 맹렬한, 집어삼킬 듯한", ipa:"dɪˈvaʊərɪŋ"},
  {en:"diligence", pos:"명", ko:"근면, 부지런함", ipa:"ˈdɪlədʒəns"},
  {en:"dingy", pos:"형", ko:"지저분한, 우중충한", ipa:"ˈdɪndʒi"},
  {en:"disappointment", pos:"명", ko:"실망", ipa:"dɪsəˈpɔɪntmənt"},
  {en:"discontent", pos:"명", ko:"불만", ipa:"dɪskənˈtɛnt"},
  {en:"disgust", pos:"동", ko:"역겹게 하다, 넌더리 나게 하다", ipa:"dɪsˈgʌst"},
  {en:"disqualify", pos:"동", ko:"자격을 박탈하다, 실격시키다", ipa:"dɪˈskwɑləfaɪ"},
  {en:"dissolved", pos:"형", ko:"해산된, 없어진", ipa:"dɪˈzɑlvd"},
  {en:"doubt", pos:"명", ko:"의심", ipa:"ˈdaʊt"},
  {en:"doubting", pos:"동", ko:"의심하기", ipa:"ˈdaʊtɪŋ"},
  {en:"drab", pos:"형", ko:"칙칙한 갈색의", ipa:"ˈdræb"},
  {en:"dropped", pos:"동", ko:"drop(떨어지다, 빠지다)의 과거형", ipa:"ˈdrɑpt"},
  {en:"duties", pos:"명", ko:"duty(직무, 의무)의 복수형", ipa:"ˈdutiz"},
  {en:"earrings", pos:"명", ko:"귀걸이", ipa:"ˈɪrɪŋz"},
  {en:"effects", pos:"명", ko:"결과, 효과", ipa:"ɪˈfɛkts"},
  {en:"effort", pos:"명", ko:"산물, 노력의 결과", ipa:"ˈɛfərt"},
  {en:"ejaculated", pos:"동", ko:"(옛 표현) 소리쳐 말하다, 외치다", ipa:"ɪˈdʒækjuleɪtɪd"},
  {en:"elbow", pos:"명", ko:"팔꿈치", ipa:"ˈɛlboʊ"},
  {en:"elderly", pos:"형", ko:"나이 지긋한", ipa:"ˈɛldərli"},
  {en:"eligible", pos:"형", ko:"자격이 있는", ipa:"ˈɛlədʒəbəl"},
  {en:"embellish", pos:"동", ko:"살을 붙여 부풀리다", ipa:"ɪmˈbɛlɪʃ"},
  {en:"emerged", pos:"동", ko:"emerge(나오다, 나타나다)의 과거형", ipa:"ɪˈmərdʒd"},
  {en:"employ", pos:"명", ko:"피고용인, 직원(옛 프랑스어투 철자 employé로 표기됨)", ipa:"ɛmˈplɔɪi"},
  {en:"employers", pos:"명", ko:"employer의 복수", ipa:"ɛmˈplɔɪərz"},
  {en:"enclosure", pos:"명", ko:"울타리 친 공간", ipa:"ɛnˈkloʊʒər"},
  {en:"endeavour", pos:"동", ko:"endeavour to ~ = ~하려고 노력하다", ipa:"ɪnˈdɛvər"},
  {en:"endeavoured", pos:"동", ko:"애쓰다, 시도하다", ipa:"ɪnˈdɛvərd"},
  {en:"engaged", pos:"형", ko:"볼일이 있어 바쁜", ipa:"ɛnˈgeɪdʒd"},
  {en:"enormous", pos:"형", ko:"막대한, 거대한", ipa:"ɪˈnɔrməs"},
  {en:"enthusiasm", pos:"명", ko:"열의", ipa:"ɪnˈθuziæzəm"},
  {en:"enthusiastic", pos:"형", ko:"열정적인", ipa:"ɪnθuziˈæstɪk"},
  {en:"entitles", pos:"동", ko:"~에게 자격을 주다", ipa:"ɛnˈtaɪtəlz"},
  {en:"enwrapped", pos:"형", ko:"(음악 등에) 깊이 빠진, 몰입한", ipa:"ɛnˈræpt"},
  {en:"especially", pos:"부", ko:"특히", ipa:"əˈspɛʃli"},
  {en:"events", pos:"명", ko:"일, 사건", ipa:"ɪˈvɛnts"},
  {en:"evident", pos:"형", ko:"분명한, 명백한", ipa:"ˈɛvədənt"},
  {en:"exactness", pos:"명", ko:"정확함", ipa:"ɪgˈzæktnəs"},
  {en:"excitement", pos:"명", ko:"흥분", ipa:"ɪkˈsaɪtmənt"},
  {en:"excuse", pos:"동", ko:"excuse me for ~ing = ~하는 것을 양해해 주세요", ipa:"ɪksˈkjuz"},
  {en:"expedition", pos:"명", ko:"원정, 탐험", ipa:"ɛkspəˈdɪʃən"},
  {en:"experience", pos:"명", ko:"경험", ipa:"ɪkˈspɪriəns"},
  {en:"explaining", pos:"동", ko:"설명하다", ipa:"ɪkˈspleɪnɪŋ"},
  {en:"extraordinary", pos:"형", ko:"놀라운, 비범한", ipa:"ɛkstrəˈɔrdənɛri"},
  {en:"fairly", pos:"부", ko:"get fairly to work = 제대로, 본격적으로 일을 시작하다", ipa:"ˈfɛrli"},
  {en:"fatal", pos:"형", ko:"치명적인", ipa:"ˈfeɪtəl"},
  {en:"faults", pos:"명", ko:"흠, 결점", ipa:"ˈfɔlts"},
  {en:"favour", pos:"명", ko:"호의", ipa:"ˈfeɪvər"},
  {en:"favourable", pos:"형", ko:"호의적인, 유리한", ipa:"ˈfeɪvərəbəl"},
  {en:"featureless", pos:"형", ko:"특징 없는", ipa:"ˈfitʃərləs"},
  {en:"features", pos:"명", ko:"이목구비, 생김새", ipa:"ˈfitʃərz"},
  {en:"fellow", pos:"명", ko:"녀석, 친구", ipa:"ˈfɛloʊ"},
  {en:"fiery", pos:"형", ko:"불타는 듯한", ipa:"ˈfaɪəri"},
  {en:"fingertips", pos:"명", ko:"손끝", ipa:"ˈfɪŋgərtɪps"},
  {en:"flame-coloured", pos:"형", ko:"불꽃색의", ipa:"ˈfleɪmkʌlərd"},
  {en:"flaming", pos:"형", ko:"불타는 듯한, 새빨간", ipa:"ˈfleɪmɪŋ"},
  {en:"florid-faced", pos:"형", ko:"얼굴이 불그레한", ipa:"ˈflɔrəd‧ˈfeɪst"},
  {en:"flushing", pos:"동", ko:"flush up to = ~까지 확 붉어지다", ipa:"ˈflʌʃɪŋ"},
  {en:"folk", pos:"명", ko:"사람들", ipa:"ˈfoʊk"},
  {en:"foolscap", pos:"명", ko:"대판 용지(옛 규격의 종이)", ipa:"ˈfulskæp"},
  {en:"footpaths", pos:"명", ko:"보도, footpath(인도)의 복수형", ipa:"ˈfʊtpæθs"},
  {en:"forefinger", pos:"명", ko:"집게손가락", ipa:"ˈfɔrfɪŋgər"},
  {en:"forehead", pos:"명", ko:"이마", ipa:"ˈfɔrhɛd"},
  {en:"forfeit", pos:"동", ko:"(규칙을 어겨서) ~을 잃다, 몰수당하다", ipa:"ˈfɔrfɪt"},
  {en:"forger", pos:"명", ko:"위조범", ipa:"ˈfɔrdʒər"},
  {en:"formidable", pos:"형", ko:"만만치 않은, 무서운", ipa:"ˈfɔrmədəbəl"},
  {en:"fortunate", pos:"형", ko:"운 좋은", ipa:"ˈfɔrtʃənət"},
  {en:"fortune", pos:"명", ko:"운, 행운", ipa:"ˈfɔrtʃən"},
  {en:"fortunes", pos:"명", ko:"운, 형편", ipa:"ˈfɔrtʃənz"},
  {en:"frankly", pos:"부", ko:"솔직하게", ipa:"ˈfræŋkli"},
  {en:"fraud", pos:"명", ko:"사기, 협잡", ipa:"ˈfrɔd"},
  {en:"frayed", pos:"형", ko:"닳아 해진", ipa:"ˈfreɪd"},
  {en:"Freemason", pos:"명", ko:"프리메이슨(비밀 공제조합원)", ipa:"ˈfrimeɪsən"},
  {en:"frock-coat", pos:"명", ko:"프록코트(예복용 긴 상의)", ipa:"ˈfrɑk‧ˈkoʊt"},
  {en:"gentleman", pos:"명", ko:"신사, 이분", ipa:"ˈdʒɛntəlmən"},
  {en:"gesture", pos:"명", ko:"몸짓, 동작", ipa:"ˈdʒɛstʃər"},
  {en:"gilt", pos:"형", ko:"금박을 입힌", ipa:"ˈgɪlt"},
  {en:"gipsy", pos:"명", ko:"집시(gypsy의 다른 철자)", ipa:"ˈdʒɪpsi"},
  {en:"glances", pos:"명", ko:"곁눈질, 흘낏 봄", ipa:"ˈglænsɪz"},
  {en:"gloomily", pos:"부", ko:"침울하게, 우울하게", ipa:"ˈgluməli"},
  {en:"gospel", pos:"명", ko:"복음", ipa:"ˈgɑspəl"},
  {en:"gravely", pos:"부", ko:"근엄하게, 심각하게", ipa:"ˈgreɪvli"},
  {en:"graver", pos:"형", ko:"grave(심각한)의 비교급, 더 심각한", ipa:"ˈgreɪvər"},
  {en:"greatcoat", pos:"명", ko:"긴 외투", ipa:"ˈgreɪtkoʊt"},
  {en:"grievance", pos:"명", ko:"불만, 불만 사유", ipa:"ˈgrivəns"},
  {en:"groan", pos:"명", ko:"신음, 탄식", ipa:"ˈgroʊn"},
  {en:"grotesque", pos:"형", ko:"기괴한", ipa:"groʊˈtɛsk"},
  {en:"grown", pos:"형", ko:"다 자란, 성인의", ipa:"ˈgroʊn"},
  {en:"habit", pos:"명", ko:"습관", ipa:"ˈhæbət"},
  {en:"hammered", pos:"동", ko:"hammered on to = ~에 못 박듯 박아 넣다", ipa:"ˈhæmərd"},
  {en:"handy", pos:"형", ko:"손재주가 있는, 일 잘하는", ipa:"ˈhændi"},
  {en:"hanging", pos:"동", ko:"매달려 있다", ipa:"ˈhæŋɪŋ"},
  {en:"hansoms", pos:"명", ko:"hansom((당시의) 이륜마차)의 복수형", ipa:"ˈhænsəmz"},
  {en:"hardly", pos:"부", ko:"거의 ~ 아니다", ipa:"ˈhɑrdli"},
  {en:"hawk-like", pos:"형", ko:"매처럼 생긴, 매부리 같은", ipa:"ˈhɔklaɪk"},
  {en:"heavily", pos:"부", ko:"크게, 세게", ipa:"ˈhɛvəli"},
  {en:"helper", pos:"명", ko:"조력자", ipa:"ˈhɛlpər"},
  {en:"hesitate", pos:"동", ko:"망설이다, 주저하다", ipa:"ˈhɛzəteɪt"},
  {en:"hoax", pos:"명", ko:"사기, 속임수(장난삼아 속이는 것)", ipa:"ˈhoʊks"},
  {en:"hobby", pos:"명", ko:"취미", ipa:"ˈhɑbi"},
  {en:"household", pos:"명", ko:"가족, 가정", ipa:"ˈhaʊshoʊld"},
  {en:"humdrum", pos:"형", ko:"따분하고 단조로운", ipa:"ˈhʌmdrʌm"},
  {en:"identify", pos:"동", ko:"알아보다, 식별하다", ipa:"aɪˈdɛntəfaɪ"},
  {en:"imagination", pos:"명", ko:"상상력", ipa:"ɪmædʒəˈneɪʃən"},
  {en:"improving", pos:"동", ko:"향상시키다", ipa:"ɪmˈpruvɪŋ"},
  {en:"improvisations", pos:"명", ko:"즉흥 연주(들)", ipa:"ɪmprɑvɪˈzeɪʃənz"},
  {en:"indeed", pos:"부", ko:"정말로", ipa:"ɪnˈdid"},
  {en:"indicated", pos:"동", ko:"나타내다, 보여주다", ipa:"ˈɪndəkeɪtəd"},
  {en:"indications", pos:"명", ko:"단서, 표시", ipa:"ɪndəˈkeɪʃənz"},
  {en:"injustice", pos:"명", ko:"부당함, 불공정", ipa:"ɪnˈdʒʌstɪs"},
  {en:"inquired", pos:"동", ko:"inquire(묻다)의 과거형", ipa:"ɪnˈkwaɪərd"},
  {en:"inspection", pos:"명", ko:"살펴봄, 관찰", ipa:"ɪnˈspɛkʃən"},
  {en:"instance", pos:"명", ko:"사례, 경우", ipa:"ˈɪnstəns"},
  {en:"instantly", pos:"부", ko:"곧바로, 즉시", ipa:"ˈɪnstəntli"},
  {en:"instructions", pos:"명", ko:"instruction의 복수", ipa:"ɪnˈstrʌkʃənz"},
  {en:"insult", pos:"동", ko:"모욕하다", ipa:"ɪnˈsʌlt"},
  {en:"intelligence", pos:"명", ko:"지성, 지능", ipa:"ɪnˈtɛlədʒəns"},
  {en:"interfere", pos:"동", ko:"지장을 주다, 간섭하다", ipa:"ɪntərˈfɪr"},
  {en:"introspect", pos:"동", ko:"성찰하다, 내면을 들여다보다", ipa:"ˈɪntrəspɛkt"},
  {en:"introspective", pos:"형", ko:"자기 성찰적인", ipa:"ɪntrəˈspɛktɪv"},
  {en:"intrusion", pos:"명", ko:"불쑥 끼어듦, 방해", ipa:"ɪnˈtruʒən"},
  {en:"intuition", pos:"명", ko:"직관", ipa:"ɪntuˈɪʃən"},
  {en:"issues", pos:"명", ko:"issue(문제, 쟁점)의 복수형", ipa:"ˈɪʃuz"},
  {en:"judgment", pos:"명", ko:"판단", ipa:"ˈdʒʌdʒmənt"},
  {en:"judicial", pos:"형", ko:"판단을 내리는", ipa:"dʒuˈdɪʃəl"},
  {en:"keen-witted", pos:"형", ko:"예리한, 기지가 넘치는", ipa:"ˈkinˌwɪtɪd"},
  {en:"keenly", pos:"부", ko:"예리하게, 날카롭게", ipa:"ˈkinli"},
  {en:"kindness", pos:"명", ko:"친절", ipa:"ˈkaɪndnəs"},
  {en:"labour", pos:"명", ko:"노동", ipa:"ˈleɪbər"},
  {en:"landlord", pos:"명", ko:"집주인", ipa:"ˈlændlɔrd"},
  {en:"languid", pos:"형", ko:"나른한", ipa:"ˈlæŋgwəd"},
  {en:"languor", pos:"명", ko:"나른함, 무기력", ipa:"ˈlæŋgər"},
  {en:"late", pos:"형", ko:"고인이 된", ipa:"ˈleɪt"},
  {en:"laughed", pos:"동", ko:"웃다(과거형)", ipa:"ˈlæft"},
  {en:"laurel", pos:"명", ko:"월계수", ipa:"ˈlɔrəl"},
  {en:"lengthened", pos:"동", ko:"길어졌다", ipa:"ˈlɛŋθənd"},
  {en:"liberty", pos:"명", ko:"실례를 무릅쓴 자유", ipa:"ˈlɪbərti"},
  {en:"literature", pos:"명", ko:"문헌, 저술", ipa:"ˈlɪtərətʃər"},
  {en:"living", pos:"명", ko:"생계", ipa:"ˈlɪvɪŋ"},
  {en:"loftily", pos:"부", ko:"거만하게", ipa:"ˈlɔftɪli"},
  {en:"lord", pos:"명", ko:"(감탄) 주님, 하느님", ipa:"ˈlɔrd"},
  {en:"lust", pos:"명", ko:"여기서는 열망, 갈망", ipa:"ˈlʌst"},
  {en:"maintenance", pos:"명", ko:"유지, 존속", ipa:"ˈmeɪntənəns"},
  {en:"mantelpiece", pos:"명", ko:"벽난로 선반", ipa:"ˈmæntəlpis"},
  {en:"manual", pos:"형", ko:"손으로 하는, 육체의", ipa:"ˈmænjuəl"},
  {en:"manufactory", pos:"명", ko:"제조 공장", ipa:"mænjəˈfæktəri"},
  {en:"merely", pos:"부", ko:"그저, 단지", ipa:"ˈmɪrli"},
  {en:"merit", pos:"명", ko:"훌륭함, 재능", ipa:"ˈmɛrət"},
  {en:"mind", pos:"명", ko:"정신", ipa:"ˈmaɪnd"},
  {en:"mistake", pos:"명", ko:"실수", ipa:"mɪˈsteɪk"},
  {en:"moods", pos:"명", ko:"기분, 상태", ipa:"ˈmudz"},
  {en:"mopping", pos:"동", ko:"(땀 등을) 닦다", ipa:"ˈmɑpɪŋ"},
  {en:"mortals", pos:"명", ko:"mortal(인간, 보통 사람)의 복수형", ipa:"ˈmɔrtəlz"},
  {en:"mysterious", pos:"형", ko:"이해할 수 없는, 불가사의한", ipa:"mɪˈstɪriəs"},
  {en:"narrative", pos:"명", ko:"이야기, 진술", ipa:"ˈnærətɪv"},
  {en:"nocturnal", pos:"형", ko:"밤의, 야간의", ipa:"nɑkˈtərnəl"},
  {en:"nodding", pos:"동", ko:"nod(꾸벅꾸벅 졸다, 끄덕이다)의 -ing형", ipa:"ˈnɑdɪŋ"},
  {en:"nominal", pos:"형", ko:"명목상의", ipa:"ˈnɑmənəl"},
  {en:"note", pos:"명", ko:"~을 적어두다", ipa:"ˈnoʊt"},
  {en:"obese", pos:"형", ko:"비만인, 뚱뚱한", ipa:"oʊˈbis"},
  {en:"obliging", pos:"형", ko:"기꺼이 돕는, 고분고분한", ipa:"əˈblaɪdʒɪŋ"},
  {en:"observed", pos:"동", ko:"말했다", ipa:"əbˈzɜrvd"},
  {en:"occasionally", pos:"부", ko:"때때로", ipa:"əˈkeɪʒənəli"},
  {en:"occupation", pos:"명", ko:"직업", ipa:"ɑkjəˈpeɪʃən"},
  {en:"occupations", pos:"명", ko:"occupation의 복수", ipa:"ɑkjəˈpeɪʃənz"},
  {en:"offices", pos:"명", ko:"사무실", ipa:"ˈɔfəsəz"},
  {en:"ominous", pos:"형", ko:"불길한", ipa:"ˈɑmənəs"},
  {en:"oppressed", pos:"형", ko:"짓눌린, 억눌린", ipa:"əˈprɛst"},
  {en:"oppressively", pos:"부", ko:"답답할 만큼, 지나치게", ipa:"əˈprɛsɪvli"},
  {en:"order", pos:"명", ko:"조합, 결사", ipa:"ˈɔrdər"},
  {en:"ornament", pos:"명", ko:"장식", ipa:"ˈɔrnəmənt"},
  {en:"orphanage", pos:"명", ko:"고아원", ipa:"ˈɔrfənədʒ"},
  {en:"overcoat", pos:"명", ko:"외투", ipa:"ˈoʊvərkoʊt"},
  {en:"overtopped", pos:"동", ko:"완전히 압도했다", ipa:"oʊvərˈtɑpt"},
  {en:"paint", pos:"명", ko:"여기서는 화장품/안료(가짜로 머리를 붉게 칠하는 것)", ipa:"ˈpeɪnt"},
  {en:"partner", pos:"명", ko:"동료", ipa:"ˈpɑrtnər"},
  {en:"patch", pos:"명", ko:"자국, 얼룩", ipa:"ˈpætʃ"},
  {en:"pavement", pos:"명", ko:"보도, 인도(영국식 표현)", ipa:"ˈpeɪvmənt"},
  {en:"pawnbroker's", pos:"명", ko:"전당포 주인", ipa:"ˈpɔnbroʊkərz"},
  {en:"pea-jacket", pos:"명", ko:"피코트(짧고 두꺼운 상의)", ipa:"ˈpiˌdʒækət"},
  {en:"peculiar", pos:"형", ko:"~에만 있는, ~특유의", ipa:"pəˈkjuljər"},
  {en:"pedestrians", pos:"명", ko:"보행자들", ipa:"pəˈdɛstriənz"},
  {en:"pensioner", pos:"명", ko:"연금 수급자", ipa:"ˈpɛnʃənər"},
  {en:"perceive", pos:"동", ko:"알아차리다, 감지하다", ipa:"pərˈsiv"},
  {en:"personally", pos:"부", ko:"as far as ~ personally concerned = ~ 개인적으로만 보면", ipa:"ˈpərsənəli"},
  {en:"persuaded", pos:"동", ko:"persuade oneself that ~ = 스스로 ~라고 믿어버리다", ipa:"pərˈsweɪdɪd"},
  {en:"photography", pos:"명", ko:"사진술, 사진 촬영", ipa:"fəˈtɑgrəfi"},
  {en:"pierced", pos:"동", ko:"pierced for earrings = 귀걸이를 하기 위해 뚫린", ipa:"ˈpɪrst"},
  {en:"piling", pos:"동", ko:"쌓아올리다", ipa:"ˈpaɪlɪŋ"},
  {en:"planked", pos:"동", ko:"planked down = (돈을) 척 내놓다", ipa:"ˈplæŋkt"},
  {en:"planted", pos:"동", ko:"(단단히) 짚다, 놓다", ipa:"ˈplæntɪd"},
  {en:"plunged", pos:"동", ko:"갑자기 달려들다, 뛰어들다", ipa:"ˈplʌndʒd"},
  {en:"poky", pos:"형", ko:"비좁은", ipa:"ˈpoʊki"},
  {en:"pompous", pos:"형", ko:"거들먹거리는", ipa:"ˈpɑmpəs"},
  {en:"portly", pos:"형", ko:"뚱뚱하고 풍채 좋은", ipa:"ˈpɔrtli"},
  {en:"positive", pos:"형", ko:"확실한, 명백한", ipa:"ˈpɑzətɪv"},
  {en:"prank", pos:"명", ko:"장난, 짓궂은 짓", ipa:"ˈpræŋk"},
  {en:"precaution", pos:"명", ko:"예방 조치, 조심", ipa:"priˈkɔʃən"},
  {en:"predominated", pos:"동", ko:"predominate(우세하다, 지배하다)의 과거형", ipa:"prɪˈdɑməneɪtɪd"},
  {en:"premises", pos:"명", ko:"(건물이 딸린) 부지, 사무실(항상 복수형)", ipa:"ˈprɛməsəz"},
  {en:"presented", pos:"동", ko:"내놓다, 제시하다", ipa:"priˈzɛntɪd"},
  {en:"press", pos:"명", ko:"여기서는 인쇄기가 아니라 문 달린 장롱/벽장(영국식)", ipa:"ˈprɛs"},
  {en:"presume", pos:"동", ko:"(완곡하게) 짐작하다, 추측하다", ipa:"prɪˈzum"},
  {en:"pride", pos:"명", ko:"자부심, 으쓱함", ipa:"ˈpraɪd"},
  {en:"private", pos:"형", ko:"private word = 은밀한 이야기, 개인적인 이야기", ipa:"ˈpraɪvət"},
  {en:"promises", pos:"동", ko:"~일 듯하다", ipa:"ˈprɑməsəz"},
  {en:"prompt", pos:"형", ko:"신속한, 지체 없는", ipa:"ˈprɑmpt"},
  {en:"prompted", pos:"동", ko:"~하도록 부추기다", ipa:"ˈprɑmptɪd"},
  {en:"promptly", pos:"부", ko:"지체 없이, 즉시", ipa:"ˈprɑmptli"},
  {en:"propagation", pos:"명", ko:"번식, 확산", ipa:"prɑpəˈgeɪʃən"},
  {en:"proposition", pos:"명", ko:"주장, 명제", ipa:"prɑpəˈzɪʃən"},
  {en:"prove", pos:"동", ko:"(결과적으로) ~로 판명되다, 드러나다", ipa:"ˈpruv"},
  {en:"puckered", pos:"형", ko:"찌푸려 주름진", ipa:"ˈpʌkərd"},
  {en:"purely", pos:"부", ko:"순전히", ipa:"ˈpjʊrli"},
  {en:"puzzling", pos:"형", ko:"알쏭달쏭하게 하는, 헷갈리게 하는", ipa:"ˈpʌzəlɪŋ"},
  {en:"questioning", pos:"형", ko:"의아해하는, 캐묻는 듯한", ipa:"ˈkwɛstʃənɪŋ"},
  {en:"quietly", pos:"부", ko:"조용히", ipa:"ˈkwaɪətli"},
  {en:"quill-pen", pos:"명", ko:"깃펜", ipa:"ˈkwɪlˌpɛn"},
  {en:"quitted", pos:"동", ko:"quit(떠나다)의 과거형", ipa:"ˈkwɪtɪd"},
  {en:"rabbit", pos:"명", ko:"토끼", ipa:"ˈræbət"},
  {en:"realise", pos:"동", ko:"실감하다, 깨닫다(영국식 철자)", ipa:"ˈriəlaɪz"},
  {en:"reason", pos:"명", ko:"이성, 사고력", ipa:"ˈrizən"},
  {en:"recall", pos:"동", ko:"기억해내다, 떠올리다", ipa:"rɪˈkɔl"},
  {en:"recommence", pos:"동", ko:"다시 시작하다", ipa:"rikəˈmɛns"},
  {en:"refreshingly", pos:"부", ko:"신선하게, 새롭게 느껴질 만큼", ipa:"riˈfrɛʃɪŋli"},
  {en:"relapsing", pos:"동", ko:"도로 몸을 파묻다", ipa:"rɪˈlæpsɪŋ"},
  {en:"relentless", pos:"형", ko:"가차 없는, 냉철한", ipa:"rɪˈlɛntlɪs"},
  {en:"relish", pos:"명", ko:"즐기는 마음, 애호", ipa:"ˈrɛlɪʃ"},
  {en:"remark", pos:"동", ko:"말하다, 언급하다", ipa:"rɪˈmɑrk"},
  {en:"remarkable", pos:"형", ko:"놀라운, 뛰어난", ipa:"rɪˈmɑrkəbəl"},
  {en:"remarked", pos:"동", ko:"말했다", ipa:"rɪˈmɑrkt"},
  {en:"reputation", pos:"명", ko:"평판, 명성", ipa:"rɛpjəˈteɪʃən"},
  {en:"requirement", pos:"명", ko:"요건, 자격 요건", ipa:"rɪˈkwaɪrmənt"},
  {en:"rest", pos:"동", ko:"괴다, 얹어두다", ipa:"ˈrɛst"},
  {en:"retired", pos:"형", ko:"여기서는 한적한, 외진(원래는 은퇴한)", ipa:"rɪˈtaɪrd"},
  {en:"roar", pos:"명", ko:"a roar of laughter = 웃음보가 터짐, 폭소", ipa:"ˈrɔr"},
  {en:"roof", pos:"명", ko:"살 곳을 지키다", ipa:"ˈruf"},
  {en:"room", pos:"명", ko:"여지", ipa:"ˈrum"},
  {en:"routine", pos:"명", ko:"늘 하는 일", ipa:"ruˈtin"},
  {en:"rubber", pos:"명", ko:"(브리지 같은 카드 게임의) 한 판, 한 세트", ipa:"ˈrʌbər"},
  {en:"rueful", pos:"형", ko:"침울한, 후회스러운", ipa:"ˈrufəl"},
  {en:"sad-faced", pos:"형", ko:"수심에 찬 얼굴의", ipa:"ˈsædˌfeɪst"},
  {en:"salary", pos:"명", ko:"급여, 봉급", ipa:"ˈsæləri"},
  {en:"satisfied", pos:"형", ko:"만족한", ipa:"ˈsætəsfaɪd"},
  {en:"save", pos:"전", ko:"~을 제외하고", ipa:"ˈseɪv"},
  {en:"scales", pos:"명", ko:"비늘", ipa:"ˈskeɪlz"},
  {en:"scratch", pos:"명", ko:"맨 처음부터", ipa:"ˈskrætʃ"},
  {en:"seized", pos:"동", ko:"꽉 붙잡다, 움켜쥐다", ipa:"ˈsizd"},
  {en:"services", pos:"명", ko:"업무, 직무", ipa:"ˈsərvəsəz"},
  {en:"settee", pos:"명", ko:"긴 소파", ipa:"sɛˈti"},
  {en:"shabby-genteel", pos:"형", ko:"초라하지만 격식은 차린", ipa:"ˈʃæbidʒɛnˈtil"},
  {en:"shade", pos:"명", ko:"색조, 색의 종류", ipa:"ˈʃeɪd"},
  {en:"shelf", pos:"명", ko:"선반", ipa:"ˈʃɛlf"},
  {en:"shiny", pos:"형", ko:"반질반질한, 윤이 나는", ipa:"ˈʃaɪni"},
  {en:"shipwreck", pos:"명", ko:"난파", ipa:"ˈʃɪprɛk"},
  {en:"shoving", pos:"동", ko:"shove(밀치다)의 현재분사", ipa:"ˈʃʌvɪŋ"},
  {en:"shutters", pos:"명", ko:"(가게) 셔터, 덧문", ipa:"ˈʃʌtərz"},
  {en:"singular", pos:"형", ko:"기이한, 유별난", ipa:"ˈsɪŋgjələr"},
  {en:"sinking", pos:"동", ko:"sink back(뒤로 기대다)의 -ing형", ipa:"ˈsɪŋkɪŋ"},
  {en:"sleuth-hound", pos:"명", ko:"원래는 경찰견, 여기서는 명탐정", ipa:"ˈsluθˌhaʊnd"},
  {en:"slight", pos:"형", ko:"가벼운, 미미한", ipa:"ˈslaɪt"},
  {en:"smasher", pos:"명", ko:"여기서는 위조지폐범", ipa:"ˈsmæʃər"},
  {en:"smooth-faced", pos:"형", ko:"매끈한 얼굴의(수염 없는)", ipa:"ˈsmuðˌfeɪst"},
  {en:"snuff", pos:"명", ko:"코담배", ipa:"ˈsnʌf"},
  {en:"solicitor", pos:"명", ko:"(영국식) 사무 변호사", ipa:"səˈlɪsətər"},
  {en:"sound", pos:"형", ko:"건전한, 멀쩡한", ipa:"ˈsaʊnd"},
  {en:"sovereigns", pos:"명", ko:"sovereign(1파운드짜리 옛 영국 금화)의 복수형", ipa:"ˈsɑvrənz"},
  {en:"spies", pos:"명", ko:"spy(첩자)의 복수형", ipa:"ˈspaɪz"},
  {en:"spirits", pos:"명", ko:"기분이 좋은", ipa:"ˈspɪrɪts"},
  {en:"splash", pos:"명", ko:"(액체가 튄) 자국, 얼룩", ipa:"ˈsplæʃ"},
  {en:"sprang", pos:"동", ko:"spring(벌떡 일어나다, 튀어 오르다)의 과거형", ipa:"ˈspræŋ"},
  {en:"staggered", pos:"형", ko:"충격을 받아 어안이 벙벙한", ipa:"ˈstægərd"},
  {en:"stagnant", pos:"형", ko:"정체된, 고여 있는", ipa:"ˈstægnənt"},
  {en:"staining", pos:"동", ko:"물들이다", ipa:"ˈsteɪnɪŋ"},
  {en:"stake", pos:"명", ko:"판돈, 걸려 있는 것", ipa:"ˈsteɪk"},
  {en:"stalls", pos:"명", ko:"(극장의) 앞좌석, 스톨석", ipa:"ˈstɔlz"},
  {en:"stout", pos:"형", ko:"살집이 있는, 뚱뚱한", ipa:"ˈstaʊt"},
  {en:"stout-built", pos:"형", ko:"체격이 다부진", ipa:"ˈstaʊtˌbɪlt"},
  {en:"stretch", pos:"동", ko:"stretch a point = 규칙을 좀 봐주다, 예외를 두다", ipa:"ˈstrɛtʃ"},
  {en:"strict", pos:"형", ko:"엄격한", ipa:"ˈstrɪkt"},
  {en:"struggle", pos:"명", ko:"without a struggle = 저항 한번 없이, 싸워보지도 않고", ipa:"ˈstrʌgəl"},
  {en:"success", pos:"명", ko:"성공", ipa:"səkˈsɛs"},
  {en:"successful", pos:"형", ko:"성공적인", ipa:"səkˈsɛsfəl"},
  {en:"suffer", pos:"동", ko:"(안 좋은 일을) 겪다, 당하다", ipa:"ˈsʌfər"},
  {en:"suited", pos:"동", ko:"적합하다, 어울리다", ipa:"ˈsutɪd"},
  {en:"swarm", pos:"명", ko:"무리, 떼", ipa:"ˈswɔrm"},
  {en:"sympathy", pos:"명", ko:"동질감, 공감", ipa:"ˈsɪmpəθi"},
  {en:"tack", pos:"명", ko:"압정", ipa:"ˈtæk"},
  {en:"tattooed", pos:"동", ko:"문신을 새기다", ipa:"tæˈtud"},
  {en:"temporary", pos:"형", ko:"임시의, 일시적인", ipa:"ˈtɛmpərɛri"},
  {en:"thick", pos:"형", ko:"굵은, 두꺼운", ipa:"ˈθɪk"},
  {en:"thrusting", pos:"동", ko:"thrust(쑥 내밀다)의 -ing형", ipa:"ˈθrʌstɪŋ"},
  {en:"thumped", pos:"동", ko:"thump(쿵쿵 치다, 두드리다)의 과거형", ipa:"ˈθʌmpt"},
  {en:"tide", pos:"명", ko:"물결, 조류", ipa:"ˈtaɪd"},
  {en:"tint", pos:"명", ko:"색조, 색깔", ipa:"ˈtɪnt"},
  {en:"tobacconist", pos:"명", ko:"담배 가게(주인)", ipa:"təˈbækənɪst"},
  {en:"track", pos:"명", ko:"흔치 않은, 색다른", ipa:"ˈtræk"},
  {en:"tradesman", pos:"명", ko:"장사치, 상인", ipa:"ˈtreɪdzmən"},
  {en:"tramped", pos:"동", ko:"터벅터벅 걸어오다, 무거운 발걸음으로 걷다", ipa:"ˈtræmpt"},
  {en:"trick", pos:"명", ko:"수법, 요령", ipa:"ˈtrɪk"},
  {en:"trooped", pos:"동", ko:"떼 지어 걷다, 우르르 몰려가다", ipa:"ˈtrupt"},
  {en:"trousers", pos:"명", ko:"바지(영국식 표현)", ipa:"ˈtraʊzərz"},
  {en:"trustees", pos:"명", ko:"trustee의 복수", ipa:"trʌˈstiz"},
  {en:"turn", pos:"명", ko:"은혜를 베풀다", ipa:"ˈtərn"},
  {en:"unacquainted", pos:"형", ko:"잘 모르는, 익숙하지 않은", ipa:"ʌnəˈkweɪntɪd"},
  {en:"unbuttoned", pos:"형", ko:"단추를 풀어놓은", ipa:"ənˈbʌtənd"},
  {en:"uncongenial", pos:"형", ko:"마음에 안 드는, 쾌적하지 않은", ipa:"ʌnkənˈdʒinjəl"},
  {en:"understand", pos:"동", ko:"알아듣다, 이해하다", ipa:"ʌndərˈstænd"},
  {en:"unique", pos:"형", ko:"유례없는", ipa:"juˈnik"},
  {en:"upon", pos:"전", ko:"on과 같은 뜻", ipa:"əˈpɑn"},
  {en:"utmost", pos:"형", ko:"더없이 큰, 최대의", ipa:"ˈʌtmoʊst"},
  {en:"vacancy", pos:"명", ko:"결원, 공석", ipa:"ˈveɪkənsi"},
  {en:"vex", pos:"동", ko:"골치 아프게 하다, 짜증나게 하다", ipa:"ˈvɛks"},
  {en:"vice", pos:"명", ko:"나쁜 버릇, 악덕", ipa:"ˈvaɪs"},
  {en:"vigorously", pos:"부", ko:"힘차게, 세차게", ipa:"ˈvɪgərəsli"},
  {en:"vivid", pos:"형", ko:"선명한, 강렬한", ipa:"ˈvɪvəd"},
  {en:"wages", pos:"명", ko:"급여, 임금", ipa:"ˈweɪdʒəz"},
  {en:"waistcoat", pos:"명", ko:"조끼", ipa:"ˈweɪstkoʊt"},
  {en:"warmly", pos:"부", ko:"따뜻하게, 열렬히", ipa:"ˈwɔrmli"},
  {en:"wedged", pos:"동", ko:"비집고 들어가다, 쐐기처럼 끼워 넣다", ipa:"ˈwɛdʒd"},
  {en:"weedy", pos:"형", ko:"잡초가 무성한", ipa:"ˈwidi"},
  {en:"whole", pos:"명", ko:"전반적으로", ipa:"ˈhoʊl"},
  {en:"widower", pos:"명", ko:"홀아비", ipa:"ˈwɪdoʊər"},
  {en:"wig", pos:"명", ko:"가발", ipa:"ˈwɪg"},
  {en:"willing", pos:"형", ko:"기꺼이 하는", ipa:"ˈwɪlɪŋ"},
  {en:"wish", pos:"동", ko:"바라다, 소원하다", ipa:"ˈwɪʃ"},
  {en:"withdraw", pos:"동", ko:"물러나다", ipa:"wɪðˈdrɔ"},
  {en:"wits", pos:"명", ko:"어쩔 줄 모르는", ipa:"ˈwɪts"},
  {en:"wonder", pos:"동", ko:"~에 놀라다", ipa:"ˈwʌndər"},
  {en:"worth", pos:"형", ko:"~의 가치가 있는", ipa:"ˈwərθ"},
  {en:"wriggled", pos:"동", ko:"몸을 꼬다, 꿈틀대다", ipa:"ˈrɪgəld"},
  {en:"wrist", pos:"명", ko:"손목", ipa:"ˈrɪst"},
  {en:"wrung", pos:"동", ko:"wring의 과거형", ipa:"ˈrʌŋ"},
  {en:"youth", pos:"명", ko:"젊은이", ipa:"ˈjuθ"},
];
